pub mod segment;
pub mod protected;
pub mod segmenter;
pub mod session;

pub use segment::*;
pub use protected::{detect_protected_spans, ProtectedKind, ProtectedSpan};
pub use segmenter::{segment, RawBlock};
pub use session::SessionState;
pub mod plan;
pub use plan::{apply_unified_diff, replace_is_lossless, CompressionPlan, DropReason, PlanEntry, Reconstruct, SegmentAction};
pub mod planner;
pub use planner::{Pass, PlanCtx, Planner, stability_order};
pub mod task;
pub use task::TaskSignal;
pub mod passes;
pub use passes::SupersessionPass;
pub use passes::ExactDedupPass;
pub use passes::RelevancePass;
pub use passes::IvmDeltaPass;
pub mod emit;
pub use emit::{emit, EmittedSegment, FidelityReport};
